[project]
name = "ai-healthcare-assisstant"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "google-genai>=1.28.0",
    "python-dotenv>=1.1.1",
    "streamlit>=1.47.1",
]
